services:
  # --- BOT ---
  - type: web
    name: inko-shop-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: true
    envVars:
      # фикс версии Python, чтобы не падало на 3.13
      - key: PYTHON_VERSION
        value: 3.11.9

      # секреты/переменные бота
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false

      # ссылка на Render-сайт
      - key: SHOP_URL
        value: https://inko-webapp.onrender.com

  # --- WEBAPP (STATIC SITE) ---
  - type: web
    name: inko-webapp
    runtime: static
    staticPublishPath: docs
    autoDeploy: true
